#stable urls

last_tag:
    path: /bundle/{bundle}/tag/last
    defaults: { method: 'lastTag', defaults: {'type': 'stable'} }

last_available_tag:
    path: /bundle/{bundle}/coreVersion/{coreVersion}/installable
    defaults: { method: 'lastInstallableTag', defaults: {'type': 'stable'} }

download_tag:
    path: /bundle/{bundle}/tag/{tag}/download
    defaults: { method: 'downloadTag', defaults: {'type': 'stable'} }

download_last:
    path: /bundle/{bundle}/coreVersion/{coreVersion}/download
    defaults: { method: 'downloadLast', defaults: {'type': 'stable'} }

available_tags:
    path: /bundle/{bundle}/tag/available
    defaults: { method: 'availableTags', defaults: {'type': 'stable'} }

last_tags:
    path: /version/{coreVersion}/tags/last
    defaults: { method: 'lastInstallableTags', defaults: {'type': 'stable'} }

#test urls

last_tag_test:
    path: /bundle/{bundle}/tag/last/test
    defaults: { method: 'lastTag', defaults: {'type': 'test'} }

last_available_tag_test:
    path: /bundle/{bundle}/coreVersion/{coreVersion}/installable/test
    defaults: { method: 'lastInstallableTag', defaults: {'type': 'test'} }

download_tag_test:
    path: /bundle/{bundle}/tag/{tag}/download/test
    defaults: { method: 'downloadTag', defaults: {'type': 'test'} }

download_last_test:
    path: /bundle/{bundle}/coreVersion/{coreVersion}/download/test
    defaults: { method: 'downloadLast', defaults: {'type': 'test'} }

available_tags_test:
    path: /bundle/{bundle}/tag/available/test
    defaults: { method: 'availableTags', defaults: {'type': 'test'} }

last_tags_test:
    path: /version/{coreVersion}/tags/last/test
    defaults: { method: 'lastInstallableTags', defaults: {'type': 'test'} }

#github hook

new_release:
    path: /release/add
    defaults: { method: addRelease }
