last_tag:
    path: /bundle/{bundle}/tag/last
    defaults: { method: 'lastTag' }

last_available_tag:
    path: /bundle/{bundle}/coreVersion/{coreVersion}/installable
    defaults: { method: 'lastInstallableTag' }

download_tag:
    path: /bundle/{bundle}/tag/{tag}/download
    defaults: { method: 'downloadTag' }

download_last:
    path: /bundle/{bundle}/coreVersion/{coreVersion}/download
    defaults: { method: 'downloadLast' }

available_tags:
    path: /bundle/{bundle}/tag/available
    defaults: { method: 'availableTags' }

new_release:
    path: /release/add
    defaults: { method: addRelease }

last_tags:
    path: /version/{coreVersion}/tags/last
    defaults: { method: 'lastInstallableTags' }
